n = input('Digite algo: ')

print(n, "O tipo primitivo desse valor é", type(n))
print('É alfanúmerico? {}'.format(n.isalnum()))
print('É alfabético?', n.isalpha())
print('Pertence a tabela Asci?', n.isascii())
print('É Decimal?', n.isdecimal())
print('É um digito decimal?', n.isdigit())
print('Funciona como identificador?',n.isidentifier())
print('É somente Minúscula?', n.islower())
print('É somente númerico?', n.isnumeric())
print('É printável?', n.isprintable())
print('É somente espaços?', n.isspace())
print('Está capitalizada?', n.istitle())
print('É somente maiusculas?', n.isupper())