name = str(input("Digite seu nome completo: ")).strip()
divide = name.split()
print("Muito prazer em te conhecer!")
print("Seu primeiro nome é {}.".format(divide[0]))
print("Seu último nome é {}.".format(divide[len(divide)-1]))
